/**
 * Shared default configurations for automation components.
 * Extracted from individual components to a single source of truth.
 */

export const DEFAULT_TEMPLATES = [
  { id: 1, pipeline: 'P1', stage: 'New Lead', timing: 'On entry', recipient: 'Client', name: 'Speed-to-Lead Intro', content: 'Hi {{name}}! This is {{agent_name}} with Forged Financial. I saw you were interested in life insurance — I\'d love to help! When\'s a good time to chat?', requiredVars: ['name', 'agent_name'] },
  { id: 2, pipeline: 'P1', stage: 'Contact', timing: '4-day exit', recipient: 'Client', name: 'Farewell SMS', content: 'Hi {{name}}, we haven\'t been able to connect. If you ever need help with life insurance, don\'t hesitate to reach out to {{agent_name}} at {{agent_phone}}. Take care!', requiredVars: ['name', 'agent_name'] },
  { id: 3, pipeline: 'P1', stage: 'Engaged', timing: 'On entry', recipient: 'Client', name: 'Interest Gauge', content: 'Hi {{name}}, thanks for your interest! I\'d love to learn more about what you\'re looking for. Do you have a few minutes to chat this week?', requiredVars: ['name'] },
  { id: 4, pipeline: 'P1', stage: 'Qualified', timing: '48h no activity', recipient: 'Client', name: 'Qualified Check-in', content: 'Hey {{name}}, just checking in! We\'re making great progress on finding the right coverage for you. Any questions I can answer?', requiredVars: ['name'] },
  { id: 5, pipeline: 'P1', stage: 'App Process', timing: '24h no activity', recipient: 'Client', name: 'App Process Check-in', content: 'Hi {{name}}, your application is in progress! Just need a couple more details to keep things moving. Can you give me a call when you have a moment?', requiredVars: ['name'] },
  { id: 6, pipeline: 'P1', stage: 'Closed Won', timing: 'On entry', recipient: 'Client', name: 'Submission Reminder', content: 'Hi {{name}}, great news — your application has been submitted to {{carrier}}! Your agent {{agent_name}} ({{agent_phone}}) will keep you updated.', requiredVars: ['name', 'carrier', 'agent_name'] },
  { id: 7, pipeline: 'P1', stage: 'Closed Won', timing: '+5 min', recipient: 'Client', name: 'Congratulations', content: 'Congratulations {{name}}! 🎉 Your {{face_amount}} policy with {{carrier}} is submitted. We\'ll let you know as soon as it\'s approved!', requiredVars: ['name', 'carrier'] },
  { id: 8, pipeline: 'P3', stage: 'Approved', timing: 'On entry', recipient: 'Client', name: 'Approval Congrats', content: 'Great news {{name}}! Your application with {{carrier}} has been APPROVED! 🎉 {{agent_name}} will reach out with next steps.', requiredVars: ['name', 'carrier', 'agent_name'] },
  { id: 9, pipeline: 'P3', stage: 'Draft Cleared', timing: 'On entry', recipient: 'Client', name: 'Payment Confirmed', content: 'Hi {{name}}, your first payment for your {{carrier}} policy has cleared successfully! Your coverage is now active. Welcome aboard! 🎉', requiredVars: ['name', 'carrier'] },
  { id: 10, pipeline: 'P4', stage: 'New Exception', timing: 'On entry', recipient: 'Agent', name: 'Exception Alert', content: '🚨 EXCEPTION ALERT: Policy {{policy_number}} for {{name}} has an issue. Check P4 immediately.', requiredVars: ['name', 'policy_number'] },
  { id: 11, pipeline: 'P4', stage: 'New Exception', timing: '+4h', recipient: 'Agent', name: 'Second Exception Alert', content: '⚠️ REMINDER: Exception for {{name}} ({{policy_number}}) still unresolved after 4 hours. Please take action.', requiredVars: ['name', 'policy_number'] },
  { id: 12, pipeline: 'P4', stage: 'Active Recovery', timing: 'On entry', recipient: 'Client', name: 'Issue Notification', content: 'Hi {{name}}, we noticed an issue with your {{carrier}} policy. Please contact {{agent_name}} at {{agent_phone}} to resolve this quickly.', requiredVars: ['name', 'carrier', 'agent_name'] },
  { id: 13, pipeline: 'P4', stage: 'Resolved', timing: 'On resolution', recipient: 'Client + Agent', name: 'Resolution Confirmation', content: 'Good news {{name}}! The issue with your {{carrier}} policy has been resolved. Your coverage is active and in good standing. ✅', requiredVars: ['name', 'carrier'] },
  { id: 14, pipeline: 'P4', stage: 'Daily', timing: '8AM', recipient: 'Agent', name: 'RE Pipeline Summary', content: 'Good morning! Your RE pipeline summary: {{summary}}. Check your dashboard for details.', requiredVars: [] },
  { id: 15, pipeline: 'P5', stage: 'Recycle', timing: 'Day 1', recipient: 'Agent', name: 'Recycle Day 1', content: '📋 Re-contact reminder: {{name}} entered Recycle. Consider reaching out to explore rewrite options.', requiredVars: ['name'] },
  { id: 16, pipeline: 'P5', stage: 'Recycle', timing: 'Day 15', recipient: 'Agent', name: 'Recycle Day 15', content: '📋 Mid-cycle reminder: {{name}} has been in Recycle for 15 days. Time for a follow-up attempt.', requiredVars: ['name'] },
  { id: 17, pipeline: 'P5', stage: 'Recycle', timing: 'Day 30', recipient: 'Agent', name: 'Recycle Day 30', content: '📋 Final attempt: {{name}} has been in Recycle for 30 days. Last chance before moving to Uninsurable.', requiredVars: ['name'] },
  { id: 18, pipeline: 'P6', stage: 'Month 1', timing: 'On entry', recipient: 'Client', name: 'Month 1 Gift', content: 'Hi {{name}}! It\'s been 1 month since your policy started. Thank you for trusting us with your coverage! 🎁', requiredVars: ['name'] },
  { id: 19, pipeline: 'P6', stage: 'Month 3', timing: 'On entry', recipient: 'Client', name: 'Month 3 Thank You', content: 'Hi {{name}}, 3 months in! Just wanted to say thank you for being a valued client. Everything going well with your {{carrier}} policy?', requiredVars: ['name', 'carrier'] },
  { id: 20, pipeline: 'P6', stage: 'Month 6', timing: 'On entry', recipient: 'Client', name: 'Month 6 Beneficiary Check', content: 'Hi {{name}}, it\'s been 6 months! Quick reminder — have there been any life changes that might affect your beneficiary designations?', requiredVars: ['name'] },
  { id: 21, pipeline: 'P6', stage: 'Month 12', timing: 'On entry', recipient: 'Client', name: 'Anniversary', content: 'Happy policy anniversary {{name}}! 🎉 It\'s been a full year. If you need any changes or have questions, {{agent_name}} is here for you.', requiredVars: ['name', 'agent_name'] },
  { id: 22, pipeline: 'P7', stage: 'Nurture', timing: 'Day 7', recipient: 'Client', name: 'Nurture Day 7', content: 'Hey {{name}}, life gets busy — totally understand! Just wanted you to know I\'m still here whenever you\'re ready to chat about coverage options. — {{agent_name}}', requiredVars: ['name', 'agent_name'] },
  { id: 23, pipeline: 'P7', stage: 'Nurture', timing: 'Day 45', recipient: 'Client', name: 'Nurture Day 45', content: 'Hi {{name}}, carriers have adjusted their rates recently. Might be worth taking another look! Let me know if you\'d like an updated quote. — {{agent_name}}', requiredVars: ['name', 'agent_name'] },
  { id: 24, pipeline: 'P7', stage: 'Nurture', timing: 'Day 60', recipient: 'Client', name: 'Nurture Day 60', content: 'Thinking of you {{name}}! Coverage is one of those things that\'s always better to have sooner rather than later. I\'m here when you\'re ready. — {{agent_name}}', requiredVars: ['name', 'agent_name'] },
  { id: 25, pipeline: 'P7', stage: 'Nurture', timing: 'Day 90', recipient: 'Client', name: 'Nurture Day 90', content: 'Hi {{name}}, still looking for the right life insurance? I have some new options that might be a great fit. Want to take a look? — {{agent_name}}', requiredVars: ['name', 'agent_name'] },
  { id: 26, pipeline: 'P7', stage: 'Nurture', timing: 'Day 135', recipient: 'Client', name: 'Nurture Day 135', content: 'Hey {{name}}, just a mid-cycle check-in. Things change — if your situation is different now, I\'d love to help find the right coverage. — {{agent_name}}', requiredVars: ['name', 'agent_name'] },
  { id: 27, pipeline: 'P7', stage: 'Nurture', timing: 'Day 180', recipient: 'Client', name: 'Nurture Day 180', content: 'Hi {{name}}, it\'s been a while! I\'m still here if you ever need help with life insurance. No pressure — just know the door is always open. — {{agent_name}}', requiredVars: ['name', 'agent_name'] },
]

export const DEFAULT_TIMERS = [
  { id: 'p1-new-lead', pipeline: 'P1 - Sales', stage: 'New Lead', duration: 3, unit: 'days', min: 1, max: 7, enabled: true, destination: 'Contact' },
  { id: 'p1-contact', pipeline: 'P1 - Sales', stage: 'Contact', duration: 4, unit: 'days', min: 1, max: 10, enabled: true, destination: 'Nurture (P7)' },
  { id: 'p1-engaged', pipeline: 'P1 - Sales', stage: 'Engaged Interest', duration: 14, unit: 'days', min: 3, max: 30, enabled: true, destination: 'Nurture (P7)' },
  { id: 'p1-qualified', pipeline: 'P1 - Sales', stage: 'Qualified Interest', duration: 7, unit: 'days', min: 2, max: 14, enabled: true, destination: 'Nurture (P7)' },
  { id: 'p1-app', pipeline: 'P1 - Sales', stage: 'Application Process', duration: 11, unit: 'days', min: 3, max: 21, enabled: true, destination: 'Nurture (P7)' },
  { id: 'p4-recovery', pipeline: 'P4 - Retention', stage: 'Active Recovery', duration: 30, unit: 'days', min: 7, max: 60, enabled: true, destination: 'Terminated' },
  { id: 'p7-nurture', pipeline: 'P7 - Nurture', stage: 'Nurture', duration: 180, unit: 'days', min: 30, max: 365, enabled: true, destination: 'Recycle (P5)' },
  { id: 'p5-recycle', pipeline: 'P5 - Recycle', stage: 'Recycle', duration: 45, unit: 'days', min: 14, max: 90, enabled: true, destination: 'Uninsurable' },
  { id: 'p5-rewrite', pipeline: 'P5 - Recycle', stage: 'Rewrite', duration: 7, unit: 'days', min: 3, max: 14, enabled: true, destination: 'Recycle' },
]
